# Generated by Django 2.2.24 on 2024-12-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('property', '0004_auto_20241124_2257'), ('property', '0005_auto_20241124_2323'), ('property', '0006_auto_20241124_2332')]

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Новостройка'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(blank=True, db_index=True, null=True, verbose_name='Новостройка'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Новостройка'),
        ),
    ]
