# Generated by Django 2.2.24 on 2024-11-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20241124_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Новостройка'),
        ),
    ]
