# Generated by Django 2.2.24 on 2024-12-01 16:20

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_flat_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owners_pure_phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, null=True, verbose_name='Нормализованный номер владельца'),
        ),
    ]
