# Generated by Django 2.2.24 on 2024-12-01 16:24

from django.db import migrations
import phonenumbers


def normalize_phones(apps, schema_editor):
    Flats = apps.get_model('property', 'Flat')
    for flat in Flats.objects.all():
        if flat.owners_phonenumber:
            raw_number = flat.owners_phonenumber
            parsed_number = phonenumbers.parse(raw_number, 'RU')
            normalized_number = phonenumbers.format_number(parsed_number, phonenumbers.PhoneNumberFormat.E164)
            flat.owners_pure_phonenumber = normalized_number
            flat.save()         
              

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_flat_owners_pure_phonenumber'),
    ]

    operations = [
        migrations.RunPython(normalize_phones)
    ]
