# Generated by Django 2.2.24 on 2024-12-01 17:07

from django.db import migrations

def copy_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owners = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owners.objects.get_or_create(owner = flat.owner,
                                    owners_phonenumber = flat.owners_phonenumber,
                                    owners_pure_phonenumber = flat.owners_pure_phonenumber,)
        

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_owner'),
    ]

    operations = [
        migrations.RunPython(copy_owners)
    ]
