# Generated by Django 2.2.24 on 2024-12-01 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20241201_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='owner',
            new_name='flat_owner',
        ),
    ]
