# Generated by Django 2.2.24 on 2024-12-01 17:32

from django.db import migrations

def fill_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    
    
    for flat in Flat.objects.all():
        owner, created = Owner.objects.get_or_create(owner = flat.flat_owner,
                                    owners_phonenumber = flat.owners_phonenumber,
                                    owners_pure_phonenumber = flat.owners_pure_phonenumber,)
        owner.flats.add(flat)
           
    
            
        
class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20241201_2030'),
    ]

    operations = [
        migrations.RunPython(fill_flats)
    ]
